// Generated by scripts/generate-activity.mjs. Do not edit.
export const ACTIVITY_KINDS = ["reasoning", "read", "write", "edit", "apply_patch", "search", "list", "execute", "fetch", "update_tasks", "subtask", "tool"] as const
export const ACTIVITY_STATES = ["pending", "running", "completed", "failed", "cancelled", "unknown"] as const
